### ISSUE TITLE
Tracker: 2025  OpenVis Website Refresh

### ISSUE THREAD

**Issue by ibgreen** [openjs-foundation/open-visualization#24]
We are refreshing the website for early 2025
- Integrate https://vis.gl
- Modernize content / organization / styling
- Prepare for additional projects potentially  joining in the future

Tasls

- [x] Copy https://vis.gl site and content to this site @ibgreen 
- [x] Unify styling vis.gl vs openvis websites @ilyabo 
- [x] Unbreak prismic CMS integration @ilyabo 
- [ ] Restructure site / project list to prepare for additional projects joining in the future. @ilyabo 
- [ ] Redirect vis.gl domain to vis.gl content on this site. Ben

Punch List 
- [ ] Front page / initial text block: Emphasize GPU / WebGPU (not WebGL), more clearly separate mission statements from governance collaboration space sentence. (Reported by @ibgreen )
- [ ]  About page / image - Cuts off some members. Add a caption, maybe `A mix of open visualization maintainers and users meeting in London at the 2024 open visualization summit`
